when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        profiler:
            enabled: true
            collect_serializer_data: true
            collect: false
            dsn: 'file:%kernel.project_dir%/var/cache/dev/profiler'
