# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            visibility: public
            directory_visibility: public
            options:
                directory: '%storage_default_directory%'
