# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
security:
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        App\Entity\User: 'auto'
        App\Entity\Admin: 'auto'
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        api_users:
            entity:
                class: App\Entity\User
        admin_users:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        admin:
            pattern: ^/admin
            provider: admin_users
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: admin
            logout:
                path: admin_logout
        api_login:
            pattern: ^/auth
            stateless: true
            provider: api_users
            json_login:
                username_path: username
                check_path: /auth
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/
            stateless: true
            provider: api_users
            jwt: ~

    access_control:
        - { path: ^/admin/register$, roles: PUBLIC_ACCESS } # Admin registration
        - { path: ^/admin/reset-password, roles: PUBLIC_ACCESS } # Admin password management
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS } # Admin login
        - { path: ^/admin, roles: ROLE_ADMIN } # Admin
        - { path: ^/debug, roles: PUBLIC_ACCESS } # Dev
        - { path: ^/.well-known, roles: PUBLIC_ACCESS } # ActivityPub related
        - { path: ^/ap/, roles: PUBLIC_ACCESS } # ActivityPub related
        - { path: ^/auth$, roles: PUBLIC_ACCESS } # Allows login
        - { path: ^/$, roles: PUBLIC_ACCESS } # Homepage
        - { path: ^/docs$, roles: PUBLIC_ACCESS } # API documentation
        - { path: ^/register$, roles: PUBLIC_ACCESS, methods: ['POST'] } # Allows register
        - { path: ^/profile, roles: PUBLIC_ACCESS } # Public side
        - { path: ^/instance, roles: PUBLIC_ACCESS } # Instance side
        - { path: ^/users/me, roles: IS_AUTHENTICATED_FULLY } # Own user account
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY } # Everything else

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: md5
                encode_as_base64: false
                iterations: 0
