[book]
title = "HiveCache"
authors = ["HiveCache Contributors"]
language = "en"
description = "HiveCache is a decentralized social bookmarking service based on ActivityPub."

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "coal"

[output.html.print]
enable = false

[output.html.search]
enable = false
